### ISSUE TITLE
s25edit doesn't shutdown properly on linux

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25edit#17] opened 2019-01-27 13:35 UTC
If the editor is closed, one has to press enter twice. This fooled me into believing the thread crashed, or was left as a zombie, but this isn't the case. Therefore its just a minor issue I guess: 

```
s25edit 
Expecting S2 game files in /usr/share/s25rttr/S2
Maps folder set to /home/user/.s25rttr/WORLDS
Return to the Roots Mapeditor

Initializing SDL...
Create Window...
Loading file: /GFX/PICS/SETUP997.LBM...
Loading file: /GFX/PICS/SETUP000.LBM...
Loading file: /GFX/PICS/SETUP010.LBM...
Loading file: /GFX/PICS/SETUP011.LBM...
Loading file: /GFX/PICS/SETUP012.LBM...
Loading file: /GFX/PICS/SETUP013.LBM...
Loading file: /GFX/PICS/SETUP014.LBM...
Loading file: /GFX/PICS/SETUP015.LBM...
Loading file: /GFX/PICS/SETUP666.LBM...
Loading file: /GFX/PICS/SETUP667.LBM...
Loading file: /GFX/PICS/SETUP801.LBM...
Loading file: /GFX/PICS/SETUP802.LBM...
Loading file: /GFX/PICS/SETUP803.LBM...
Loading file: /GFX/PICS/SETUP804.LBM...
Loading file: /GFX/PICS/SETUP805.LBM...
Loading file: /GFX/PICS/SETUP806.LBM...
Loading file: /GFX/PICS/SETUP810.LBM...
Loading file: /GFX/PICS/SETUP811.LBM...
Loading file: /GFX/PICS/SETUP895.LBM...
Loading file: /GFX/PICS/SETUP896.LBM...
Loading file: /GFX/PICS/SETUP897.LBM...
Loading file: /GFX/PICS/SETUP898.LBM...
Loading file: /GFX/PICS/SETUP899.LBM...
Loading file: /GFX/PICS/SETUP899.LBM...
Loading file: /GFX/PICS/SETUP990.LBM...
Loading file: /GFX/PICS/WORLD.LBM...
Loading file: /GFX/PICS/WORLDMSK.LBM...
Loading file: /DATA/TEXTURES/GOU5.DAT...
Loading file: /DATA/TEXTURES/GOU5.DAT...
Loading file: /DATA/TEXTURES/GOU6.DAT...
Loading file: /DATA/TEXTURES/GOU7.DAT...
Loading palette from file: /DATA/EDITRES.IDX...
Loading file: /DATA/EDITRES.IDX...
Loading palette from file: /DATA/IO/EDITIO.IDX...
Loading file: /DATA/IO/EDITIO.IDX...
Loading file: /DATA/EDITBOB.LST...
Loading file: /GFX/TEXTURES/TEX5.LBM...
Loading file: /GFX/TEXTURES/TEX6.LBM...
Loading file: /GFX/TEXTURES/TEX7.LBM...
Loading file: /DATA/MIS0BOBS.LST...
Loading file: /DATA/MIS1BOBS.LST...
Loading file: /DATA/MIS2BOBS.LST...
Loading file: /DATA/MIS3BOBS.LST...
Loading file: /DATA/MIS4BOBS.LST...
Loading file: /DATA/MIS5BOBS.LST...

Press ENTER to close this window . . .

```

**Comment by Flamefire** [comment] 2019-01-27 19:38
Sorry there is no easy way to fix this requiring 2 enter presses. As the issue is minor I won't fix it

**Closed by Flamefire** 2019-01-27 19:38 UTC

**Comment by stefson** [comment] 2019-01-27 19:41
ok, thanks for having a look :)
